# Generated by Django 3.1.7 on 2021-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofill', '0002_section_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
