# Generated by Django 3.2.4 on 2021-06-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autofill', '0004_question_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
