# Generated by Django 3.1.7 on 2021-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autofill', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.CharField(blank=True, choices=[('SingleElement', 'Single Element'), ('MultipleElement', 'Multiple Element')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('JawabanSingkat', 'Jawaban Singkat Display'), ('Paragraf', 'Paragraf'), ('PilihanGanda', 'Pilihan Ganda'), ('KotakCentang', 'Kotak Centang'), ('DropDown', 'DropDown'), ('SkalaLinier', 'Skala Linier'), ('KisiPilihan Ganda', 'Kisi Pilihan Ganda'), ('PetakKotak Centang', 'Petak Kotak Centang'), ('Tanggal', 'Tanggal'), ('Waktu', 'Waktu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('JawabanSingkat', 'Jawaban Singkat Display'), ('Paragraf', 'Paragraf'), ('PilihanGanda', 'Pilihan Ganda'), ('KotakCentang', 'Kotak Centang'), ('DropDown', 'DropDown'), ('SkalaLinier', 'Skala Linier'), ('KisiPilihan Ganda', 'Kisi Pilihan Ganda'), ('PetakKotak Centang', 'Petak Kotak Centang'), ('Tanggal', 'Tanggal'), ('Waktu', 'Waktu')], max_length=100, null=True),
        ),
    ]
